"""empty message

Revision ID: fc1aa4372711
Revises: b709ebdebd7a
Create Date: 2020-06-03 13:20:47.785457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc1aa4372711'
down_revision = 'b709ebdebd7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('cargo', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'cargo')
    # ### end Alembic commands ###
